using System;
using System.Collections.Generic;
using JetBrains.Annotations;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using VimeoDotNet.Enums;

namespace VimeoDotNet.Parameters
{
    /// <summary>
    /// Parameters for creating or editing a recurring live event.
    /// </summary>
    public class EditLiveEventParameters : IParameterProvider
    {
        /// <summary>
        /// The title of the event. If <see cref="AutomaticallyTitleStream"/> is <c>true</c>,
        /// this value is the base title for videos created by streaming to this event.
        /// Maps to <c>title</c>. Required.
        /// </summary>
        [PublicAPI]
        public string Title { get; set; }

        /// <summary>
        /// The title of the next video to be streamed to the event. Required when
        /// <see cref="AutomaticallyTitleStream"/> is <c>false</c>.
        /// Maps to <c>stream_title</c>.
        /// </summary>
        [PublicAPI]
        public string StreamTitle { get; set; }

        /// <summary>
        /// The description of the next video to be streamed to the event.
        /// Maps to <c>stream_description</c>.
        /// </summary>
        [PublicAPI]
        public string StreamDescription { get; set; }

        /// <summary>
        /// Whether the title for the next video in the event is generated based on the time of the
        /// stream and the <see cref="Title"/> field of the event.
        /// Maps to <c>automatically_title_stream</c>.
        /// </summary>
        [PublicAPI]
        public bool? AutomaticallyTitleStream { get; set; }

        /// <summary>
        /// The time zone used in resolving the timestamps included in automatically generated video titles.
        /// Maps to <c>time_zone</c>.
        /// </summary>
        [PublicAPI]
        public string EventTimeZone { get; set; }

        // ── Schedule ──────────────────────────────────────────────────────────

        /// <summary>
        /// The time in ISO 8601 format when the event is expected to be live.
        /// Maps to <c>schedule.start_time</c>.
        /// </summary>
        [PublicAPI]
        public DateTime? ScheduledStartTime { get; set; }

        /// <summary>
        /// The time in ISO 8601 format when the event is expected to end.
        /// Maps to <c>schedule.end_time</c>.
        /// </summary>
        [PublicAPI]
        public DateTime? ScheduledEndTime { get; set; }

        /// <summary>
        /// The recurrence rule for the event's schedule according to RFC 5545.
        /// Maps to <c>schedule.rrule</c>.
        /// </summary>
        [PublicAPI]
        public string ScheduleRRule { get; set; }

        /// <summary>
        /// The time zone used in resolving the schedule timestamps.
        /// Maps to <c>schedule.time_zone</c>.
        /// </summary>
        [PublicAPI]
        public string TimeZone { get; set; }

        // ── Privacy ───────────────────────────────────────────────────────────

        /// <summary>
        /// The initial privacy of the videos generated by streaming to the event, as well as
        /// the embed privacy of the entire collection.
        /// Maps to <c>stream_privacy.view</c>.
        /// </summary>
        [PublicAPI]
        [JsonConverter(typeof(StringEnumConverter))]
        public LiveEventPrivacyOption? Privacy { get; set; }

        /// <summary>
        /// The password when <see cref="Privacy"/> is <see cref="LiveEventPrivacyOption.Password"/>.
        /// Anyone with the password can view the videos generated by streaming to the event.
        /// Maps to <c>stream_password</c>.
        /// </summary>
        [PublicAPI]
        public string Password { get; set; }

        /// <summary>
        /// Whether the share link is usable.
        /// Maps to <c>allow_share_link</c>.
        /// </summary>
        [PublicAPI]
        public bool? AllowShareLink { get; set; }

        // ── Streaming ─────────────────────────────────────────────────────────

        /// <summary>
        /// Whether RTMP preview is enabled for the event.
        /// Maps to <c>rtmp_preview</c>.
        /// </summary>
        [PublicAPI]
        public bool? RtmpPreview { get; set; }

        /// <summary>
        /// Whether the DVR feature is enabled.
        /// Maps to <c>dvr</c>.
        /// </summary>
        [PublicAPI]
        public bool? Dvr { get; set; }

        /// <summary>
        /// The type of stream delay on the viewer side.
        /// Takes precedence over the legacy <see cref="LowLatency"/> property.
        /// Maps to <c>latency</c>.
        /// </summary>
        [PublicAPI]
        public LiveEventLatency? Latency { get; set; }

        /// <summary>
        /// The preferred streaming method.
        /// Maps to <c>preferred_stream_method</c>.
        /// </summary>
        [PublicAPI]
        public LiveEventStreamMethod? PreferredStreamMethod { get; set; }

        // ── Embed ─────────────────────────────────────────────────────────────

        /// <summary>
        /// The embed settings of the event and the videos generated by streaming to this event.
        /// Maps to the <c>embed.*</c> sub-properties.
        /// </summary>
        [PublicAPI]
        public LiveEventEmbedSettings Embed { get; set; }

        /// <summary>
        /// The embed permission level for the event.
        /// Maps to <c>stream_embed.embed</c>.
        /// </summary>
        [PublicAPI]
        public LiveEventStreamEmbedPrivacy? StreamEmbedPrivacy { get; set; }

        // ── Content ───────────────────────────────────────────────────────────

        /// <summary>
        /// A list of values describing the content in this event.
        /// Maps to <c>content_rating</c>.
        /// </summary>
        [PublicAPI]
        public List<LiveEventContentRating> ContentRating { get; set; }

        /// <summary>
        /// The order in which the videos of the event appear within the event's playlist.
        /// Maps to <c>playlist_sort</c>.
        /// </summary>
        [PublicAPI]
        public LiveEventPlaylistSort? PlaylistSort { get; set; }

        /// <summary>
        /// The URI of the folder that contains this event.
        /// Maps to <c>folder_uri</c>.
        /// </summary>
        [PublicAPI]
        public string FolderUri { get; set; }

        // ── Chat ──────────────────────────────────────────────────────────────

        /// <summary>
        /// Whether to display the live chat client on the Vimeo event page.
        /// Maps to <c>chat_enabled</c>.
        /// </summary>
        [PublicAPI]
        public bool? ChatEnabled { get; set; }

        // ── Automated Closed Captions ─────────────────────────────────────────

        /// <summary>
        /// Whether automated closed captions are enabled for the event.
        /// Maps to <c>auto_cc_enabled</c>.
        /// </summary>
        [PublicAPI]
        public bool? AutomatedClosedCaptions { get; set; }

        /// <summary>
        /// The language in which the automated closed captions appear.
        /// Accepted values: <c>de-DE</c>, <c>en-US</c>, <c>es-ES</c>, <c>fr-FR</c>, <c>pt-BR</c>.
        /// Maps to <c>auto_cc_lang</c>.
        /// </summary>
        [PublicAPI]
        public string AutomatedClosedCaptionsLanguage { get; set; }

        /// <summary>
        /// A comma-separated list of keywords that improve the quality of the automated closed captions.
        /// Maps to <c>auto_cc_keywords</c>.
        /// </summary>
        [PublicAPI]
        public string AutoCcKeywords { get; set; }

        /// <inheritdoc />
        public string ValidationError()
        {
            if (Privacy is LiveEventPrivacyOption.Password && string.IsNullOrEmpty(Password))
            {
                return "Password is required if Privacy value is set to Password.";
            }

            return null;
        }

        /// <inheritdoc />
        public IDictionary<string, string> GetParameterValues()
        {
            // title is required by the API; fall back to a placeholder if not provided
            var parameterValues = new Dictionary<string, string>
            {
                { "title", !string.IsNullOrEmpty(Title) ? Title : "Title" },
                // StreamTitle takes precedence over the legacy Description property
                { "stream_title", !string.IsNullOrEmpty(StreamTitle) ? StreamTitle : "Stream Title" }
            };

            // ── Schedule ──────────────────────────────────────────────────────
            if (ScheduledStartTime.HasValue)
                parameterValues.Add("schedule.start_time", ScheduledStartTime.Value.ToString("yyyy-MM-ddTHH:mm:ssZ"));

            if (ScheduledEndTime.HasValue)
                parameterValues.Add("schedule.end_time", ScheduledEndTime.Value.ToString("yyyy-MM-ddTHH:mm:ssZ"));

            if (!string.IsNullOrEmpty(ScheduleRRule))
                parameterValues.Add("schedule.rrule", ScheduleRRule);

            if (!string.IsNullOrEmpty(TimeZone))
                parameterValues.Add("schedule.time_zone", TimeZone);

            if (!string.IsNullOrEmpty(EventTimeZone))
                parameterValues.Add("time_zone", EventTimeZone);

            // ── Stream metadata ───────────────────────────────────────────────
            if (!string.IsNullOrEmpty(StreamDescription))
                parameterValues.Add("stream_description", StreamDescription);

            if (AutomaticallyTitleStream.HasValue)
                parameterValues.Add("automatically_title_stream", AutomaticallyTitleStream.Value.ToString().ToLower());

            // ── Privacy ───────────────────────────────────────────────────────
            if (Privacy.HasValue)
                parameterValues.Add("stream_privacy.view", Privacy.Value.GetParameterValue());

            if (!string.IsNullOrEmpty(Password))
                parameterValues.Add("stream_password", Password);

            if (AllowShareLink.HasValue)
                parameterValues.Add("allow_share_link", AllowShareLink.Value.ToString().ToLower());

            // ── Streaming ─────────────────────────────────────────────────────
            if (RtmpPreview.HasValue)
                parameterValues.Add("rtmp_preview", RtmpPreview.Value.ToString().ToLower());

            if (Dvr.HasValue)
                parameterValues.Add("dvr", Dvr.Value.ToString().ToLower());

            if (Latency.HasValue)
                parameterValues.Add("latency", Latency.Value.GetParameterValue());

            if (PreferredStreamMethod.HasValue)
                parameterValues.Add("preferred_stream_method", PreferredStreamMethod.Value.GetParameterValue());

            // ── Content ───────────────────────────────────────────────────────
            if (ContentRating is { Count: > 0 })
            {
                var contentRatings = new List<string>();
                foreach (var rating in ContentRating)
                    contentRatings.Add(rating.GetParameterValue());
                parameterValues.Add("content_rating", string.Join(",", contentRatings));
            }

            if (PlaylistSort.HasValue)
                parameterValues.Add("playlist_sort", PlaylistSort.Value.GetParameterValue());

            if (!string.IsNullOrEmpty(FolderUri))
                parameterValues.Add("folder_uri", FolderUri);

            // ── Embed ─────────────────────────────────────────────────────────
            if (StreamEmbedPrivacy.HasValue)
                parameterValues.Add("stream_embed.embed", StreamEmbedPrivacy.Value.GetParameterValue());

            if (Embed != null)
            {
                if (Embed.Autoplay.HasValue)
                    parameterValues.Add("embed.autoplay", Embed.Autoplay.Value.ToString().ToLower());
                if (!string.IsNullOrEmpty(Embed.Color))
                    parameterValues.Add("embed.color", Embed.Color);
                if (Embed.UseColor.HasValue)
                    parameterValues.Add("embed.use_color", Embed.UseColor.Value.ToString().ToLower());
                if (Embed.CustomLogoActive.HasValue)
                    parameterValues.Add("embed.logos.custom.active", Embed.CustomLogoActive.Value.ToString().ToLower());
                if (!string.IsNullOrEmpty(Embed.CustomLogoLink))
                    parameterValues.Add("embed.logos.custom.link", Embed.CustomLogoLink);
                if (Embed.CustomLogoSticky.HasValue)
                    parameterValues.Add("embed.logos.custom.sticky", Embed.CustomLogoSticky.Value.ToString().ToLower());
                if (Embed.VimeoLogo.HasValue)
                    parameterValues.Add("embed.logos.vimeo", Embed.VimeoLogo.Value.ToString().ToLower());
                if (Embed.Loop.HasValue)
                    parameterValues.Add("embed.loop", Embed.Loop.Value.ToString().ToLower());
                if (Embed.Playlist.HasValue)
                    parameterValues.Add("embed.playlist", Embed.Playlist.Value.ToString().ToLower());
                if (Embed.Schedule.HasValue)
                    parameterValues.Add("embed.schedule", Embed.Schedule.Value.ToString().ToLower());
                if (Embed.ShowLatestArchivedClip.HasValue)
                    parameterValues.Add("embed.show_latest_archived_clip", Embed.ShowLatestArchivedClip.Value.ToString().ToLower());
            }

            // ── Chat ──────────────────────────────────────────────────────────
            if (ChatEnabled.HasValue)
                parameterValues.Add("chat_enabled", ChatEnabled.Value.ToString().ToLower());

            // ── Automated Closed Captions ─────────────────────────────────────
            if (AutomatedClosedCaptions.HasValue)
                parameterValues.Add("auto_cc_enabled", AutomatedClosedCaptions.Value.ToString().ToLower());

            if (!string.IsNullOrEmpty(AutomatedClosedCaptionsLanguage))
                parameterValues.Add("auto_cc_lang", AutomatedClosedCaptionsLanguage);

            if (!string.IsNullOrEmpty(AutoCcKeywords))
                parameterValues.Add("auto_cc_keywords", AutoCcKeywords);

            return parameterValues.Keys.Count > 0 ? parameterValues : null;
        }
    }
}
