using JetBrains.Annotations;

namespace VimeoDotNet.Parameters;

/// <summary>
/// Embed settings for a live event and the videos generated by streaming to this event.
/// </summary>
public class LiveEventEmbedSettings
{
    /// <summary>
    /// Whether playback starts automatically on load.
    /// Maps to <c>embed.autoplay</c>.
    /// </summary>
    [PublicAPI]
    public bool? Autoplay { get; set; }

    /// <summary>
    /// The hexadecimal color code for the main color of the embed player.
    /// Maps to <c>embed.color</c>.
    /// </summary>
    [PublicAPI]
    public string Color { get; set; }

    /// <summary>
    /// Whether the embed player should use (<c>true</c>) or ignore (<c>false</c>) the <see cref="Color"/> value.
    /// Maps to <c>embed.use_color</c>.
    /// </summary>
    [PublicAPI]
    public bool? UseColor { get; set; }

    /// <summary>
    /// Whether to show the custom logo on the embed player.
    /// Maps to <c>embed.logos.custom.active</c>.
    /// </summary>
    [PublicAPI]
    public bool? CustomLogoActive { get; set; }

    /// <summary>
    /// The URL that loads when the user clicks the custom logo.
    /// Maps to <c>embed.logos.custom.link</c>.
    /// </summary>
    [PublicAPI]
    public string CustomLogoLink { get; set; }

    /// <summary>
    /// Whether to show the custom logo persistently (<c>true</c>) or hide it with the rest of the UI (<c>false</c>).
    /// Maps to <c>embed.logos.custom.sticky</c>.
    /// </summary>
    [PublicAPI]
    public bool? CustomLogoSticky { get; set; }

    /// <summary>
    /// Whether to show the Vimeo logo on the embed player.
    /// Maps to <c>embed.logos.vimeo</c>.
    /// </summary>
    [PublicAPI]
    public bool? VimeoLogo { get; set; }

    /// <summary>
    /// Whether the playlist should start from the beginning again after reaching the end of the last video.
    /// Maps to <c>embed.loop</c>.
    /// </summary>
    [PublicAPI]
    public bool? Loop { get; set; }

    /// <summary>
    /// Whether to show the playlist controls on the embed player.
    /// Maps to <c>embed.playlist</c>.
    /// </summary>
    [PublicAPI]
    public bool? Playlist { get; set; }

    /// <summary>
    /// Whether to show the event schedule on the embed player.
    /// Maps to <c>embed.schedule</c>.
    /// </summary>
    [PublicAPI]
    public bool? Schedule { get; set; }

    /// <summary>
    /// Whether to show the latest archived video in the embed player when the event is off-air.
    /// Maps to <c>embed.show_latest_archived_clip</c>.
    /// </summary>
    [PublicAPI]
    public bool? ShowLatestArchivedClip { get; set; }
}
